name: pointpillars
channels:
  - bioconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - numba
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - boost
  - easydict
  - pyyaml
  - scikit-image
  - tqdm
  - pip:
    - tensorboardx
    - kornia
